<a href="https://colab.research.google.com/github/codebuzer/Bioactivity-Prediction-App/blob/main/Untitled14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import mean
import pandas as pd
import numpy as np
from numpy import std
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import RepeatedKFold
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv("toy_data_model.csv")

In [ ]:
# get the dataset
def get_dataset():
	X, y = make_multilabel_classification(n_samples=df.iloc[::], n_features=df.iloc[: , 1:337], n_classes=df.iloc[:, 337:360], n_labels=df.iloc[:,360:], random_state=1)
	return X, y

In [ ]:
X = df.iloc[:,1:361]
X.head()

,AA,AT,AG,AC,TA,TT,TG,TC,GA,GT,...,Oxazolidinone,Polymyxin,Steroid antibacterial,Pseudomonic acid,Nitroimidazole,Aldehyde,Quaternary Ammonium Compound,Quaternary Ammonium Compounds,Peroxide,Heat
0,34,33,47,41,20,24,42,31,51,35,...,0,0,0,0,0,0,0,0,0,0
1,33,33,40,40,18,19,43,29,50,31,...,0,0,0,0,0,0,0,0,0,0
2,56,57,75,65,32,40,71,52,86,54,...,0,0,0,0,0,0,0,0,0,0
3,70,80,28,22,57,35,41,24,44,24,...,0,0,0,0,0,0,0,0,0,0
4,29,38,29,28,21,26,56,23,39,24,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
y = df.iloc[:,361:]
y.head(3)

,Gentamicin,Tobramycin,Streptomycin,Spectinomycin,Amikacin,Isepamicin,Dibekacin,Kanamycin,Neomycin,Lividomycin,...,Metronidazole,Piperacillin+Clavulanic acid,Formaldehyde,Benzylkonium Chloride,Ethidium Bromide,Chlorhexidine,Cetylpyridinium Chloride,Hydrogen peroxide,Nalidixic acid,Temperature
0,0,1,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,1,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
n_features = X.iloc[:,1:336]

In [ ]:
n_features.head(3)

,AT,AG,AC,TA,TT,TG,TC,GA,GT,GG,...,CCTG,CCTC,CCGA,CCGT,CCGG,CCGC,CCCA,CCCT,CCCG,CCCC
0,33,47,41,20,24,42,31,51,35,33,...,0,1,6,5,0,0,2,0,3,1
1,33,40,40,18,19,43,29,50,31,31,...,1,1,6,5,0,0,2,0,3,1
2,57,75,65,32,40,71,52,86,54,49,...,1,3,8,8,1,2,3,0,4,1

In [ ]:
n_classes = X.iloc[:,337:362]
n_classes.head(3)

,Quinolone,Beta-lactam,Folate pathway antagonist,Fosfomycin,Glycopeptide,Lincosamide,Streptogramin A,Pleuromutilin,Macrolide,Tetracycline,...,Oxazolidinone,Polymyxin,Steroid antibacterial,Pseudomonic acid,Nitroimidazole,Aldehyde,Quaternary Ammonium Compound,Quaternary Ammonium Compounds,Peroxide,Heat
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
n_labels = y.iloc[:362:]
n_labels.head(3)

,Gentamicin,Tobramycin,Streptomycin,Spectinomycin,Amikacin,Isepamicin,Dibekacin,Kanamycin,Neomycin,Lividomycin,...,Metronidazole,Piperacillin+Clavulanic acid,Formaldehyde,Benzylkonium Chloride,Ethidium Bromide,Chlorhexidine,Cetylpyridinium Chloride,Hydrogen peroxide,Nalidixic acid,Temperature
0,0,1,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,1,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
n_inputs = n_features