<a href="https://colab.research.google.com/github/codebuzer/Bioactivity-Prediction-App/blob/main/Untitled17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
import pandas as pd
import numpy as numpy

In [ ]:
df = pd.read_csv("toy_data_model.csv")
df

,ID,AA,AT,AG,AC,TA,TT,TG,TC,GA,...,Metronidazole,Piperacillin+Clavulanic acid,Formaldehyde,Benzylkonium Chloride,Ethidium Bromide,Chlorhexidine,Cetylpyridinium Chloride,Hydrogen peroxide,Nalidixic acid,Temperature
0,aac(6')-Ib_2_M23634,34,33,47,41,20,24,42,31,51,...,0,0,0,0,0,0,0,0,0,0
1,aac(6')-Ib11_1_AY136758,33,33,40,40,18,19,43,29,50,...,0,0,0,0,0,0,0,0,0,0
2,aac(6')-30-aac(6')-Ib'_1_AJ584652,56,57,75,65,32,40,71,52,86,...,0,0,0,0,0,0,0,0,0,0
3,aac(6')-Iaj_1_AB709942,70,80,28,22,57,35,41,24,44,...,0,0,0,0,0,0,0,0,0,0
4,aac(6')-Ian_1_AP014611,29,38,29,28,21,26,56,23,39,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3143,dfrA17_9_FJ807902,47,48,27,13,36,30,33,35,25,...,0,0,0,0,0,0,0,0,0,0
3144,dfrA17_10_AM937244,47,49,27,13,36,30,33,36,26,...,0,0,0,0,0,0,0,0,0,0
3145,dfrA34_1_JYRF01000065,32,59,26,37,45,31,42,34,35,...,0,0,0,0,0,0,0,0,0,0
3146,dfrA36_1_CP038791,52,58,27,26,39,56,45,26,41,...,0,0,0,0,0,0,0,0,0,0
3147,dfrA35_1_CP024557,37,47,28,24,25,26,35,36,41,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
X = df.iloc[:,1:361]
X

,AA,AT,AG,AC,TA,TT,TG,TC,GA,GT,...,Oxazolidinone,Polymyxin,Steroid antibacterial,Pseudomonic acid,Nitroimidazole,Aldehyde,Quaternary Ammonium Compound,Quaternary Ammonium Compounds,Peroxide,Heat
0,34,33,47,41,20,24,42,31,51,35,...,0,0,0,0,0,0,0,0,0,0
1,33,33,40,40,18,19,43,29,50,31,...,0,0,0,0,0,0,0,0,0,0
2,56,57,75,65,32,40,71,52,86,54,...,0,0,0,0,0,0,0,0,0,0
3,70,80,28,22,57,35,41,24,44,24,...,0,0,0,0,0,0,0,0,0,0
4,29,38,29,28,21,26,56,23,39,24,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3143,47,48,27,13,36,30,33,35,25,29,...,0,0,0,0,0,0,0,0,0,0
3144,47,49,27,13,36,30,33,36,26,29,...,0,0,0,0,0,0,0,0,0,0
3145,32,59,26,37,45,31,42,34,35,36,...,0,0,0,0,0,0,0,0,0,0
3146,52,58,27,26,39,56,45,26,41,27,...,0,0,0,0,0,0,0,0,0,0
3147,37,47,28,24,25,26,35,36,41,37,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
y = df.iloc[:,361:]
y

,Gentamicin,Tobramycin,Streptomycin,Spectinomycin,Amikacin,Isepamicin,Dibekacin,Kanamycin,Neomycin,Lividomycin,...,Metronidazole,Piperacillin+Clavulanic acid,Formaldehyde,Benzylkonium Chloride,Ethidium Bromide,Chlorhexidine,Cetylpyridinium Chloride,Hydrogen peroxide,Nalidixic acid,Temperature
0,0,1,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,1,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3143,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3144,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3145,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3146,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3147,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
X.ndim

2

In [ ]:
y.ndim

2

In [ ]:
X.shape

(3148, 360)

In [ ]:
y.shape

(3148, 98)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=random_state)

In [ ]:
X_train.shape

(2109, 360)

In [ ]:
y_train.shape

(2109, 98)

In [ ]:
## Creating model
#embedding_vector_features=40
#model=Sequential()
#model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
#model.add(LSTM(100))
#model.add(Dense(1,activation='sigmoid'))
#model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
#print(model.summary())

In [ ]:

#from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout
from tensorflow.keras.losses import binary_crossentropy

In [ ]:
# Create the model
model = Sequential()
#model.add(LSTM(100))
model.add(LSTM(1, input_shape=(2109, 360)))
model.add(Dense(5, activation='relu', input_dim=n_features))
#model.add(LSTM(64))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(98 , activation='sigmoid'))

In [ ]:
# Compile the model
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])


#model.compile(optimizer='adam',loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])

In [ ]:
# Fit data to model
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          epochs=n_epochs,
          verbose=verbosity,
          validation_split=0.2)

Epoch 1/50

ValueError: ignored

In [ ]:
X_train.shape

(2109, 360, 401)